### PR TITLE
Revert and rewrite input settings regex matching

### LINKED ISSUE #48: Huge parts of input.settings not being processed when reinstalling a mod
When reinstalling a mod, huge parts of input.settings are ignored by this regex expression:
image
Which causes the file to become corrupted when the section is rewritten with only the modded keys and the game to completely regenerate the file in launch, removing the modded keys entirely.
This means you have to add the keys manually for modded keys to work at all.
Here's my input.settings: https://pastebin.com/xmh31wAj
I am running W3MM on Linux, if that matters.
As a workaround, you can regenerate input.settings (delete the file), then add the modded keys manually, and then set input.settings to read-only to avoid W3MM messing with it later.

### PR DESCRIPTION
**Pull request by hunkyburrito**
After some further testing, I realized that matching empty contexts (and the Version line) causes more problems than it fixes. The regex has been changed back to only matching contexts followed by valid key settings, but I have now fixed the core issue.  

The matching should use `re.findall()` instead of `re.search()` since the former matches all instances of a pattern instead of only the first. This allows us to skip empty contexts and other non-matching areas while keeping the valid matches.

Apologies for the last few bad commits, definitely should've thought about them more.

Hopefully, this fixes #48 for real this time

### CODE REVIEW

**Review by Systemcluster — APPROVED** [review]
Good approach, seems reasonable!

**Comment by Systemcluster** [comment]
> Apologies for the last few bad commits, definitely should've thought about them more.

Don't worry, I should have tested it more before merging as well 😄 I really appreciate the help!

**Comment by t0mtee** [comment]
Will this require reinstalling (like literally uninstalling and installing again) mods that edit input.settings? Because after this commit, my input.settings is getting regenerated back to default every game startup.

**Comment by t0mtee** [comment]
So I've reinstalled the mods completely - still doesn't work. Here's some possible reasons I've found:

1. The [Death] category isn't present in the modded input.settings, but it is on the regenerated.
2. Same with [EMPTY_CONTEXT]
3. Same with [LootPopup]
4. Same with [TutorialPopup]

What is common between these four are that they are all empty categories - they have no keys in them. Just adding those isn't enough to fix the problem.

5. The [InputSettings] category isn't present, which contains the line "Version=43" (43 for me, I'm on 1.32).

Reasons 1-4 don't actually need to be amended for the input.settings to work, however Reason 5 is essential. To summarise, W3MM is still taking out the [InputSettings] category, which is essential for the game to work.

I'll post this comment on the PR and on the issue.

**Pull request merged**
