### PR TITLE
Add support for the Next Gen update

### PR DESCRIPTION
**Pull request by madman-asunder**
initial implementation attempt for next gen. detects dx11 vs dx12 runtime based on exe selected. Able to install mod xml settings files into the dx11 and dx12 file list files.

### CODE REVIEW

**Comment by adam-sunderman** [comment]
I tested a fresh install and ran into an issue where my mod folder installed to Mods/myInstalledMod was written as read only. I don't know how or why. I won't have time to look into it for a while and not sure if it's a regular thing or a fluke, but if anyone already knows what this may be, let me know!

**Comment by madman-asunder** [comment]
also I didn't attempt translations

**Comment by colefuerth** [comment]
thanks so much; friendly hud wouldnt load in the mods menu until I used this fork.

**Comment by henry-hsieh** [comment]
The dx12user.settings should be tracked, too. Currently it only tracks user.settings (for DX11).

**Comment by madman-asunder** [comment]
> The dx12user.settings should be tracked, too. Currently it only tracks user.settings (for DX11).

Thank you I was not aware of that file.

**Comment by madman-asunder** [comment]
most recent change has a bug or two I've already found with reconfiguring toolbar and not being backwards compatible fully. fixing

**Comment by madman-asunder** [comment]
alright I think we are back in a stable state. let me know what you find.

**Comment by henry-hsieh** [comment]
Tested FriendlyHUD and FriendlyMeditation in DX12 version. Looks good.
Would this version be released?

**Comment by madman-asunder** [comment]
I think I will eventually upload it to nexus as a next gen version. I want to give it a solid month probably in PR format.

**Comment by Systemcluster** [comment]
Thank you for your effort! I can't test it myself at the moment, but I'll see to merge this in the next couple of days.

@adam-sunderman Are you alright with me updating the current Nexus page with this update at that point?

**Comment by madman-asunder** [comment]
Yes that is fine with me! Thanks Systemcluster!

**Comment by WTFplay4funFTW-TV** [comment]
Awesome! been waiting for a TW3MM update ever since next gen came out :)

**Comment by Silencer711** [comment]
@Systemcluster - Friendly request - you should publish a new release on Github and upload the updated mod to Nexus Mods. The community should definitely have the latest version - especially with this supporting the Next-Gen update. :)

**Pull request merged**
